import jsPDF from "jspdf";

interface CertificateData {
  batchId: string;
  result: string;
  quality: number;
  farmer: string;
  date: string;
  location: string;
  hash: string;
  sensors: {
    weight: string;
    voc: string;
    rgb: string;
    temp: string;
  };
}

export function generateCertificatePDF(data: CertificateData) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const w = doc.internal.pageSize.getWidth();
  const passed = data.result === "PASSED";

  // Background
  doc.setFillColor(13, 13, 13);
  doc.rect(0, 0, w, 297, "F");

  // Top accent bar
  if (passed) { doc.setFillColor(21, 128, 61); } else { doc.setFillColor(239, 68, 68); }
  doc.rect(0, 0, w, 8, "F");

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(28);
  doc.setTextColor(255, 255, 255);
  doc.text("AGRI_TRUST", 20, 30);

  doc.setFontSize(9);
  doc.setTextColor(153, 153, 153);
  doc.text("DECENTRALIZED EDGE-AI GRADING CERTIFICATE", 20, 38);

  // Divider
  doc.setDrawColor(51, 51, 51);
  doc.setLineWidth(0.5);
  doc.line(20, 44, w - 20, 44);

  // Status
  doc.setFontSize(22);
  if (passed) { doc.setTextColor(21, 128, 61); } else { doc.setTextColor(239, 68, 68); }
  doc.text(`GRADED: ${data.result}`, 20, 58);

  doc.setFontSize(10);
  doc.setTextColor(153, 153, 153);
  doc.text(`${data.batchId}  |  Quality Score: ${data.quality}/100`, 20, 66);

  // Divider
  doc.line(20, 72, w - 20, 72);

  // Sensor grid
  doc.setFontSize(8);
  doc.setTextColor(153, 153, 153);
  doc.text("SENSOR READINGS", 20, 82);

  const sensors = [
    { label: "WEIGHT", value: data.sensors.weight },
    { label: "VOC LEVEL", value: data.sensors.voc },
    { label: "TEMPERATURE", value: data.sensors.temp },
    { label: "COLOR (RGB)", value: data.sensors.rgb },
  ];

  let sx = 20;
  sensors.forEach((s) => {
    doc.setFontSize(7);
    doc.setTextColor(153, 153, 153);
    doc.text(s.label, sx, 92);
    doc.setFontSize(16);
    doc.setTextColor(255, 255, 255);
    doc.setFont("courier", "bold");
    doc.text(s.value, sx, 100);
    doc.setFont("helvetica", "bold");
    sx += 42;
  });

  // Divider
  doc.line(20, 108, w - 20, 108);

  // Origin
  doc.setFontSize(8);
  doc.setTextColor(153, 153, 153);
  doc.text("ORIGIN INFORMATION", 20, 118);

  const origin = [
    { label: "FARMER", value: data.farmer },
    { label: "HARVEST DATE", value: data.date },
    { label: "LOCATION", value: data.location },
  ];

  let oy = 128;
  origin.forEach((o) => {
    doc.setFontSize(7);
    doc.setTextColor(153, 153, 153);
    doc.text(o.label, 20, oy);
    doc.setFontSize(11);
    doc.setTextColor(255, 255, 255);
    doc.text(o.value, 20, oy + 6);
    oy += 16;
  });

  // Divider
  doc.line(20, oy, w - 20, oy);

  // Hash
  oy += 10;
  doc.setFontSize(8);
  doc.setTextColor(153, 153, 153);
  doc.text("DIGITAL FINGERPRINT (SHA-256)", 20, oy);
  oy += 10;

  doc.setFillColor(26, 26, 26);
  doc.setDrawColor(51, 51, 51);
  doc.rect(20, oy - 5, w - 40, 12, "FD");
  doc.setFont("courier", "normal");
  doc.setFontSize(7);
  doc.setTextColor(255, 140, 0);
  doc.text(data.hash, 24, oy + 2);
  doc.setFont("helvetica", "bold");

  // Bottom bar
  oy += 24;
  doc.setFillColor(255, 140, 0);
  doc.rect(20, oy, w - 40, 0.8, "F");

  oy += 10;
  doc.setFontSize(7);
  doc.setTextColor(153, 153, 153);
  doc.text("This certificate was generated by the Agri-Trust Decentralized Edge-AI Grading System.", 20, oy);
  doc.text("Data integrity verified via blockchain ledger. Tamper-proof and immutable.", 20, oy + 5);

  doc.save(`AgriTrust_Certificate_${data.batchId}.pdf`);
}
