# =============================================================================
# train.py
# Agri-Trust — YOLOv8 Training Script
#
# Features:
#   • Transfer learning from YOLOv8n pre-trained weights
#   • Absolute-path YAML patching (fixes Roboflow relative-path issue)
#   • Class distribution analysis + inverse-frequency weight logging
#   • Raspberry Pi Cam OV5647 simulation (via rpcam_augmentation.py)
#   • Early stopping (patience parameter)
#   • TensorBoard monitoring (auto-generated by Ultralytics)
#   • Post-training validation: mAP@50, mAP@50-95, PR curves, Confusion Matrix
#   • Per-class recall report highlighting food-safety critical classes
#
# Usage:
#   python train.py
#   python train.py --model yolov8s.pt --epochs 200 --batch 8
#   python train.py --resume python/runs/agritrust_v3/weights/last.pt
#
# Monitor training:
#   tensorboard --logdir python/runs
# =============================================================================

import argparse
import os
import shutil
import sys
import time
from pathlib import Path

import torch
import yaml
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

# Ensure project root is on PYTHONPATH
PROJECT_ROOT = Path(__file__).parent
sys.path.insert(0, str(PROJECT_ROOT))

console = Console()

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

CLASS_NAMES = [
    "blossom_end_rot",   # 0
    "fruit_cracking",    # 1
    "half_ripe",         # 2
    "mold",              # 3
    "ripe",              # 4
    "rotten",            # 5
    "unripe",            # 6
]

# Food-safety critical: these classes MUST have high recall
# NOTE: anthracnose removed from dataset (too few samples, visually ambiguous)
HIGH_RECALL_CLASSES = {"mold", "rotten"}

# Grade mapping (for reference / logging)
GRADE_MAP = {
    "ripe":             "Grade A ✅",
    "half_ripe":        "Grade B 🟡",
    "unripe":           "Grade C 🟠",
    "mold":             "Reject 🔴 [CRITICAL]",
    "rotten":           "Reject 🔴 [CRITICAL]",
    "blossom_end_rot":  "Reject 🔴",
    "fruit_cracking":   "Reject 🔴",
}


# ---------------------------------------------------------------------------
# Argument Parser
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Agri-Trust YOLOv8 Training Script",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--model", type=str,
        default=str(PROJECT_ROOT / "runs" / "agritrust_v1" / "weights" / "best.pt"),
        help="YOLOv8 weights to start from. Defaults to v2 best.pt for domain warm-start."
    )
    parser.add_argument(
        "--data", type=str,
        default=str(PROJECT_ROOT / "dataset" / "data.yaml"),
        help="Path to dataset YAML"
    )
    parser.add_argument(
        "--config", type=str,
        default=str(PROJECT_ROOT / "config" / "agritrust_train.yaml"),
        help="Path to hyperparameter YAML config"
    )
    parser.add_argument(
        "--epochs", type=int, default=200,
        help="Maximum training epochs (raised to 200 for patience=40 headroom)"
    )
    parser.add_argument(
        "--batch", type=int, default=12,
        help="Batch size — 12 is optimal for RTX 2050 4GB (~1.8GB VRAM). Max safe: 12."
    )
    parser.add_argument(
        "--patience", type=int, default=50,
        help="Early-stopping patience (epochs without mAP@50 improvement)"
    )
    parser.add_argument(
        "--imgsz", type=int, default=640,
        help="Input image size"
    )
    parser.add_argument(
        "--workers", type=int, default=4,
        help="DataLoader workers (4 is stable for laptops)"
    )
    parser.add_argument(
        "--device", type=str, default=None,
        help="Training device: '0', '0,1', 'cpu'. Auto-detects CUDA if omitted."
    )
    parser.add_argument(
        "--resume", type=str, default=None,
        help="Path to last.pt checkpoint to resume training from"
    )
    parser.add_argument(
        "--no-rpcam", action="store_true",
        help="Disable RP Cam augmentation simulation"
    )
    parser.add_argument(
        "--analyze-classes", action="store_true",
        help="Run class distribution analysis before training"
    )
    return parser.parse_args()


# ---------------------------------------------------------------------------
# YAML Path Patcher
# ---------------------------------------------------------------------------

def patch_data_yaml(original_yaml_path: Path) -> Path:
    """
    Roboflow exports data.yaml with relative paths like '../train/images'.
    These break when Ultralytics resolves them from the working directory.
    This function writes a patched copy with absolute paths.

    Args:
        original_yaml_path: Path to the original data.yaml

    Returns:
        Path to the patched YAML (saved alongside the original as data_abs.yaml)
    """
    with open(original_yaml_path, "r") as f:
        data = yaml.safe_load(f)

    dataset_dir = original_yaml_path.parent

    # Resolve each split path to an absolute path
    for key in ("train", "val", "test"):
        if key in data:
            raw = data[key]
            # Handle relative paths
            candidate = (dataset_dir / raw).resolve()
            if candidate.exists():
                data[key] = str(candidate)
            else:
                # Try interpreting relative to dataset dir directly
                alt = (dataset_dir / Path(raw).name).resolve()
                if alt.exists():
                    data[key] = str(alt)
                else:
                    # Best guess: dataset_dir / split_name / images
                    split_name = Path(raw).parts[-2] if len(Path(raw).parts) >= 2 else key
                    guessed = dataset_dir / split_name / "images"
                    data[key] = str(guessed)
                    console.print(
                        f"[yellow]⚠️  Could not resolve '{raw}' — using guessed path: {guessed}[/]"
                    )

    patched_path = original_yaml_path.parent / "data_abs.yaml"
    with open(patched_path, "w") as f:
        yaml.dump(data, f, default_flow_style=False, sort_keys=False)

    console.print(f"[green]✅ Patched data YAML → {patched_path}[/]")
    return patched_path


# ---------------------------------------------------------------------------
# Device Detection
# ---------------------------------------------------------------------------

def detect_device(override: str = None) -> str:
    """Auto-detect best available device or use the override."""
    if override:
        return override
    if torch.cuda.is_available():
        device_name = torch.cuda.get_device_name(0)
        vram_gb = torch.cuda.get_device_properties(0).total_memory / 1e9
        console.print(
            f"[green]🖥️  CUDA detected: {device_name} ({vram_gb:.1f} GB VRAM)[/]"
        )
        return "0"
    console.print("[yellow]⚠️  No CUDA found — training on CPU (very slow)[/]")
    return "cpu"


# ---------------------------------------------------------------------------
# RP Cam Augmentation Callback
# ---------------------------------------------------------------------------

def build_rpcam_callback(enabled: bool = True):
    """
    Returns an Ultralytics 'on_train_start' callback that injects the
    RP Cam augmentation pipeline into the training dataset.

    Injection strategy:
      Ultralytics YOLODataset stores transforms in `dataset.transforms.transforms`
      (a list). The Albumentations wrapper object inside that list exposes a
      `.transform` attribute. We replace that transform with our RP Cam pipeline.
      Falls back silently if the structure differs across Ultralytics versions.
    """
    if not enabled:
        return None

    def inject_rpcam(trainer) -> None:
        try:
            from rpcam_augmentation import get_rpcam_pipeline
            rpcam_pipeline = get_rpcam_pipeline()

            if rpcam_pipeline is None:
                return

            # Access the training dataset through the trainer's data loader
            train_dataset = trainer.train_loader.dataset

            injected = False
            # Walk through the composed transforms to find the Albumentations wrapper
            if hasattr(train_dataset, "transforms") and hasattr(
                train_dataset.transforms, "transforms"
            ):
                for t in train_dataset.transforms.transforms:
                    # Ultralytics wraps Albumentations in a class with .transform attr
                    if hasattr(t, "transform") and t.transform is not None:
                        t.transform = rpcam_pipeline
                        injected = True
                        break

            if injected:
                console.print(
                    "[green]✅ RP Cam OV5647 augmentation injected into training pipeline[/]"
                )
            else:
                console.print(
                    "[yellow]⚠️  RP Cam augmentation could not be injected "
                    "(Albumentations wrapper not found in transforms). "
                    "Built-in Ultralytics augmentation will be used instead.[/]"
                )
        except Exception as exc:
            console.print(f"[yellow]⚠️  RP Cam injection error: {exc}[/]")

    return inject_rpcam


# ---------------------------------------------------------------------------
# Per-class Recall Reporting Callback
# ---------------------------------------------------------------------------

def build_epoch_end_callback():
    """
    Returns an 'on_fit_epoch_end' callback that logs per-class recall
    for the food-safety critical classes after each validation pass.
    """
    def log_recall(trainer) -> None:
        try:
            metrics = trainer.metrics
            # Ultralytics stores per-class results in trainer.validator.metrics
            if not hasattr(trainer, "validator") or trainer.validator is None:
                return

            names = trainer.validator.names  # dict {idx: name}
            ap_per_class = getattr(trainer.validator.metrics, "ap_class_index", None)

            # Try to access per-class precision/recall from the speed attribute
            # This is version-dependent; log what's available
            if hasattr(trainer.validator.metrics, "box"):
                box_metrics = trainer.validator.metrics.box
                if hasattr(box_metrics, "maps"):
                    maps = box_metrics.maps  # per-class mAP@50:95
                    for idx, name in names.items():
                        if name in HIGH_RECALL_CLASSES and idx < len(maps):
                            ap = maps[idx]
                            flag = "🔴" if ap < 0.70 else "✅"
                            console.print(
                                f"  {flag} [bold]{name}[/] mAP@50:95 = {ap:.4f}"
                                + (" ← BELOW TARGET" if ap < 0.70 else "")
                            )
        except Exception:
            pass  # Metrics structure varies; never crash training

    return log_recall


# ---------------------------------------------------------------------------
# Post-training Report
# ---------------------------------------------------------------------------

def print_validation_report(results, run_dir: Path) -> None:
    """Print a formatted summary of post-training validation metrics."""
    console.print()
    console.print(
        Panel.fit(
            "[bold green]📊 Agri-Trust — Post-Training Validation Report[/]",
            border_style="green",
        )
    )

    table = Table(show_header=True, header_style="bold cyan")
    table.add_column("Metric", style="bold", min_width=20)
    table.add_column("Value", justify="right")

    try:
        # Ultralytics results object exposes these attributes
        table.add_row("mAP@50",      f"{results.box.map50:.4f}")
        table.add_row("mAP@50-95",   f"{results.box.map:.4f}")
        table.add_row("Precision",   f"{results.box.mp:.4f}")
        table.add_row("Recall",      f"{results.box.mr:.4f}")
    except AttributeError:
        table.add_row("Results", "See Ultralytics run output above")

    console.print(table)

    # Artefact locations
    artifacts_table = Table(show_header=True, header_style="bold magenta")
    artifacts_table.add_column("Artefact", style="bold")
    artifacts_table.add_column("Location")
    artifacts_table.add_row("Best weights",        str(run_dir / "weights" / "best.pt"))
    artifacts_table.add_row("Last weights",        str(run_dir / "weights" / "last.pt"))
    artifacts_table.add_row("Confusion matrix",    str(run_dir / "confusion_matrix.png"))
    artifacts_table.add_row("PR curve",            str(run_dir / "PR_curve.png"))
    artifacts_table.add_row("TensorBoard logs",    str(run_dir))

    console.print()
    console.print(artifacts_table)
    console.print()
    console.print(
        f"[cyan]📈 Launch TensorBoard:[/]  [bold]tensorboard --logdir {run_dir.parent}[/]"
    )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    args = parse_args()

    # ── Banner ──────────────────────────────────────────────────────────────
    console.print(
        Panel.fit(
            "[bold green]🍅 Agri-Trust — YOLOv8 Training Pipeline[/]\n"
            f"Model: [cyan]{args.model}[/]  |  Epochs: [cyan]{args.epochs}[/]  |  "
            f"Batch: [cyan]{args.batch}[/]  |  Patience: [cyan]{args.patience}[/]",
            border_style="green",
        )
    )

    # ── Class Analysis ──────────────────────────────────────────────────────
    if args.analyze_classes:
        console.print("\n[bold]Running class distribution analysis...[/]")
        try:
            from class_analysis import main as run_analysis
            run_analysis()
        except Exception as e:
            console.print(f"[yellow]⚠️  Class analysis skipped: {e}[/]")

    # ── Device ──────────────────────────────────────────────────────────────
    device = detect_device(args.device)

    # ── Data YAML (patch relative paths) ────────────────────────────────────
    data_yaml_path = Path(args.data)
    if not data_yaml_path.exists():
        console.print(f"[red]❌ Data YAML not found: {data_yaml_path}[/]")
        sys.exit(1)

    patched_yaml = patch_data_yaml(data_yaml_path)

    # ── Load Ultralytics YOLO ────────────────────────────────────────────────
    try:
        from ultralytics import YOLO
    except ImportError:
        console.print(
            "[red]❌ ultralytics not installed. Run: pip install ultralytics[/]"
        )
        sys.exit(1)

    # ── Model Initialisation ─────────────────────────────────────────────────
    if args.resume:
        resume_path = Path(args.resume)
        if not resume_path.exists():
            console.print(f"[red]❌ Resume checkpoint not found: {resume_path}[/]")
            sys.exit(1)
        console.print(f"[yellow]🔁 Resuming from: {resume_path}[/]")
        model = YOLO(str(resume_path))
    else:
        console.print(f"[green]📦 Loading pre-trained weights: {args.model}[/]")
        model = YOLO(args.model)

    # ── Register Callbacks ───────────────────────────────────────────────────
    rpcam_callback = build_rpcam_callback(enabled=not args.no_rpcam)
    if rpcam_callback:
        model.add_callback("on_train_start", rpcam_callback)

    epoch_end_callback = build_epoch_end_callback()
    model.add_callback("on_fit_epoch_end", epoch_end_callback)

    # ── Training ─────────────────────────────────────────────────────────────
    console.print("\n[bold green]🚀 Starting training...[/]\n")
    start_time = time.time()

    train_args = dict(
        data=str(patched_yaml),
        epochs=args.epochs,
        batch=args.batch,
        imgsz=args.imgsz,
        device=device,
        workers=args.workers,
        cache="disk",          # cache preprocessed images to disk → faster from epoch 2+
        patience=args.patience,
        # ── Loss Gains ─────────────────────────────────────────────────────
        # 3 ambiguous classes removed → 7-class dataset is more balanced.
        # cls lowered from 2.0 to 1.5 — less aggressive penalization needed
        # now that anthracnose/brown_rugose/sunscald are gone.
        box=7.5,
        cls=1.5,
        dfl=1.5,
        # ── Optimizer ──────────────────────────────────────────────────────
        optimizer="AdamW",
        lr0=0.0005,           # lower LR: weights already domain-tuned from v2 best.pt
        lrf=0.01,
        warmup_epochs=3.0,    # less warmup needed — starting from trained weights
        cos_lr=True,          # cosine LR decay → smoother convergence vs step decay
        # ── Transfer Learning ───────────────────────────────────────────────
        # freeze=0: backbone is already domain-tuned from v2 — no need to protect it.
        # Full end-to-end fine-tuning from epoch 1.
        freeze=0,
        # ── Regularization ─────────────────────────────────────────────────
        dropout=0.05,         # reduced: 7-class dataset is balanced; 0.15 was over-regularizing
        label_smoothing=0.1,  # reduces overconfidence, consistently boosts mAP on small-class sets
        # ── Augmentation ───────────────────────────────────────────────────
        hsv_h=0.015,
        hsv_s=0.70,
        hsv_v=0.40,
        degrees=10.0,
        translate=0.10,
        scale=0.50,
        shear=2.0,
        flipud=0.10,
        fliplr=0.50,
        mosaic=1.0,
        mixup=0.10,
        copy_paste=0.30,      # raised: synthetic augmentation for rare classes (fruit_cracking)
        close_mosaic=20,      # turn off mosaic 20 epochs before end for fine-tuning
        # ── Output ─────────────────────────────────────────────────────────
        project=str(PROJECT_ROOT / "runs"),
        name="agritrust_v3",
        exist_ok=True,
        plots=True,
        verbose=True,
        save_period=10,
    )

    # If resuming, Ultralytics handles the resume internally
    if args.resume:
        train_args["resume"] = True

    results = model.train(**train_args)

    elapsed = time.time() - start_time
    console.print(
        f"\n[green]✅ Training complete in {elapsed/3600:.1f}h "
        f"({elapsed/60:.0f} min)[/]"
    )

    # ── Post-training Validation ─────────────────────────────────────────────
    console.print("\n[bold]Running final validation...[/]")

    run_dir = PROJECT_ROOT / "runs" / "agritrust_v3"
    best_weights = run_dir / "weights" / "best.pt"

    if best_weights.exists():
        val_model = YOLO(str(best_weights))
        val_results = val_model.val(
            data=str(patched_yaml),
            imgsz=args.imgsz,
            device=device,
            plots=True,
            save_json=True,
        )
        print_validation_report(val_results, run_dir)
    else:
        console.print(
            f"[yellow]⚠️  best.pt not found at {best_weights} — skipping final val[/]"
        )

    # ── TensorBoard Launch Hint ──────────────────────────────────────────────
    console.print()
    console.print(
        Panel(
            f"[bold cyan]Monitor with TensorBoard:[/]\n\n"
            f"  [green]tensorboard --logdir {PROJECT_ROOT / 'runs'}[/]\n\n"
            f"Then open: [link=http://localhost:6006]http://localhost:6006[/link]",
            title="📈 TensorBoard",
            border_style="cyan",
        )
    )


if __name__ == "__main__":
    main()
